version: '3.5'
services:
  generator:
    container_name: ${PROJECT_NAME}_generator
    build:
      context: ./
      dockerfile: Dockerfile
      target: generator
    command: npm run watch-chokidar
    volumes:
      - ./lib:/usr/app/lib
      - ./public:/usr/app/public
      - ./src:/usr/app/src
      - ./website:/usr/app/website
      - /usr/app/node_modules

  devserver:
    container_name: ${PROJECT_NAME}_devserver
    build:
      context: ./
      target: devserver
    command: npm run serve
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
